# Generated by Django 2.1.2 on 2019-03-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lppm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='penelitian',
            name='lokasi_id',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='pengabdian',
            name='lokasi_id',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
